### ISSUE TITLE
Global section is not picked up.

### ISSUE THREAD

**Issue by zhenyun** [linkedin/naarad#277] opened 2014-09-02 17:49 UTC
The `ts_start` and `ts_end` defined in Global Section are not picked up. 

e.g.,   
http://zzhuang-ld1/naarad.test/

**Comment by zhenyun** [comment] 2015-02-18 21:22
the issue persists...

**Comment by feng-tao** [comment] 2015-03-26 04:11
hi, I root cause and fix this bug. The fix works on my example config. Is there anyone could give a try on my fix?

**Comment by richardhsu** [comment] 2015-03-26 04:14
Please push your changes to a branch on your forked repository, that way one of us can pull the changes and test on our system as well with our own configurations and/or logs.

Might also be helpful to paste the config example you used and what log you used.

**Comment by feng-tao** [comment] 2015-03-26 16:51
push the fix to my local branch(https://github.com/feng-tao/naarad/tree/bug_227)

**Comment by richardhsu** [comment] 2015-03-27 21:30
Pull request #327 has been merged and fixes this.

**Closed by richardhsu** 2015-03-27 21:30 UTC
Labels: bug
